version: '3'
services: 
        cap_angular:
                image: cap_angular
                container_name: cap_angular
                ports: 
                        - 3000:4200
                build: 
                        context: ./docker
                        dockerfile: AngularDockerfile
                depends_on:
                        - cap_angular_express
                volumes: 
                        - ./angular:/angular
                networks: 
                        - cap_angular_net
                working_dir: /angular
                entrypoint: ["sh","start.sh"]

        cap_angular_express:
                image: cap_angular_express
                build:
                        context: ./docker
                        dockerfile: ExpressDockerfile
                container_name: cap_angular_express
                user: "node"
                expose:
                        - 3000
                ports: 
                        - 3001:3000
                volumes: 
                        - ./express:/home/node/app
                working_dir: /home/node/app
                environment:
                        - NODE_ENV=development
                depends_on:
                        - cap_angular_mongo
                networks:
                        - cap_angular_net
                entrypoint: ["sh","start.sh"]

        cap_angular_mongo: 
                image: cap_angular_mongo
                build:
                        context: ./docker
                        dockerfile: MongoDockerfile
                restart: always
                container_name: cap_angular_mongo
                volumes: 
                        - mongoconfig:/data/configdb
                        - mongodata:/data/db
                expose:
                        - 27017
                ports: 
                        - 5600:27017
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
                        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
                        - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
                networks: 
                        - cap_angular_net

networks:
        cap_angular_net:
                driver: bridge

volumes: 
        mongoconfig:
        mongodata:
